### ISSUE TITLE
Console warning cannot update during an existing state transition

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/react-component-library#154]
#### Describe the bug
On initial load warning displays path=/story/intro-overview--px-blue-react-components

Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
    in Unknown (created by Context.Consumer)
    in WithTheme(Component)
    in WithTheme(Component) (created by Preview)
    in div (created by Context.Consumer)
    in Side (created by FlexBar)
    in div (created by Context.Consumer)
    in Styled(div) (created by FlexBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in SimpleBar...

#### What is the expected behavior?
no warning

#### What are the steps to reproduce?
1. Run react storybook
2. Dev tools

#### What is your environment?

 Framework
- [ ] Angular
- [ ] React
- [ ] Ionic
- [ ] React Native

 Browser
- [ ] Internet Explorer
- [ ] Edge
- [ ] Safari
- [X] Chrome
- [X] Firefox

 Operating System
- [ ] MacOS
- [X] Windows
- [ ] Other

**Comment by joebochill** [comment]
This appears to be an upstream bug in the @storybook-addons plugin (https://github.com/storybookjs/storybook/issues/10204). Disabling the plugin makes the error go away, so that's one way we could fix it but we would lose the viewport dropdown picker (not sure how valuable that is). It also appears to be resolved in storybook 6.

**Comment by emclaug2** [comment]
I'm putting `wont-fix` labels on anything related to storybook at this point.  Closing this issue.
