### ISSUE TITLE
Shared Menu Component

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/react-component-library#181]
#### Describe the desired behavior
DropdownToolbar and UserMenu should share a common Menu component

#### Describe the current behavior
Currently, both components implement the menu and ~90% of the code is the same between the two.

#### Additional Context

The UserMenu adds the header piece, but that could be part of the shared component that the DropdownToolbar just doesn't use. 
Would we want to document this as a new component that users could use on its own with their own 'trigger' element?

**Comment by joebochill** [comment]
This could potentially allow us to move away from using the DrawerNavGroup and InfoListItem and use a regular ListItem with height 48 instead. #183

**Comment by joebochill** [comment]
This may no longer be necessary if we're going to be deprecating the DropdownToolbar component

**Comment by emclaug2** [comment]
I'm going to re-open this to review with the team; I'd like to close this issue since I'm fine with the UserMenu & ToolbarMenu menus being separate implementations.
