### ISSUE TITLE
Storybook issues when toggling theme

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/react-component-library#244]
#### Describe the bug
There are some hardcoded colors values in some places that cause some undesired behavior when toggling the themes (e.g., scorecard badge icon backgrounds, list item backgrounds, etc.).

#### What is the expected behavior?
As much as possible, components should look correct when toggling between themes. We should be taking colors from the theme where we can instead of using hardcoded values that only look good for the light theme.\

#### What are the steps to reproduce?
1. Open the storybook
2. Go to the scorecard full config story
3. Toggle to dark mode
4. Observe the hero

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/29152776/108702757-af228d80-74d7-11eb-97b2-ff1d24d3c5e0.png)
		
#### Anything else to add?
Note, there are also a number of instances where values are being set by the knobs (e.g., for the drawer full config story, almost everything is a knob). This causes the component to look absolutely horrible when switching to dark mode because nearly every color is effectively hardcoded by the knobs...it might be nice to see if we can find a way to 'reset' the colors when toggling the theme.

**Comment by emclaug2** [comment]
Can we set the knobs to be undefined so we inherit the dark theme defaults for our components?

**Comment by joebochill** [comment]
Probably not worth spending a lot of time on this if we are considering rolling our own component playground.

**Comment by emclaug2** [comment]
Closing this issue; component doc redesign on the horizon.
