### ISSUE TITLE
Use the latest version of enzyme-adapter-react

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/react-component-library#264]
#### Describe the desired behavior
Use the latest official enzyme-adapter for react 17

#### Describe the current behavior
Official version only supports up to version 16. Currently using an unofficial version.

#### Is this request related to a current issue?
https://github.com/enzymejs/enzyme/issues/2429

**Comment by joebochill** [comment]
As of today, there is still no official version for react 17

**Comment by emclaug2** [comment]
I'm putting a `needs-review` label on this; we're on React 18 now so not sure if this issue is still up-to-date.

**Comment by bkarambe** [comment]
@jeffvg is going to verify this, whether this is needed.

**Comment by joebochill** [comment]
Have we replaced all of the enzyme tests? Can we close this now? @jeffvg

**Comment by bkarambe** [comment]
We have pulled out all the enzyme tests. Closing it.
