### ISSUE TITLE
Add an activeIcon prop

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/react-component-library#294]
#### Describe the desired behavior

I've noticed a few design trends where when a drawer item turns active, the icon changes from an outlined version into a filled version. Like this:

![image](https://user-images.githubusercontent.com/8997218/122479060-7e8bc580-cf98-11eb-8110-8ce9bd46bd6c.png)

Having an `activeIcon` prop might be useful here to do the icon switch.

#### Describe the current behavior

User has to manually do the switch

#### Additional Context

Leaving this feature request here for discussion. Still need to log bugs on ng and rn side.

**Comment by joebochill** [comment]
Need to decide if this is common enough to justify adding new props / ng content for this. Right now the user can conditionally swap the icon based on the active ID.

**Comment by joebochill** [comment]
It's probably worth discussing if we want to turn this into a formal pattern of some sort

**Comment by jeffvg** [comment]
lets add a code example to this issues and close the issue
