### ISSUE TITLE
React component library loads incorrect theme in Storybook

### ISSUE THREAD

**Issue by ektasawant** [brightlayer-ui/react-component-library#326]
#### Describe the bug
`theme.palette.primary.main` is loading `#3f51b5`, which is neither the [default theme](https://mui.com/customization/default-theme/) of MUI (`#42a5f5`) nor the default for PXBlue themes.

#### What is the expected behaviour?
Similar to other react repository `theme.palette.primary.main` should load `#007BC1`
#### What are the steps to reproduce?
1. Use theme.palette.primary.main in component's storybook.
2. Check `color` CSS property

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/10433274/136992614-311d2112-1558-4b25-9a7b-3783a7fb6081.png)

#### Environment

- [X] Chrome
- [X] Safari 
- [X] Edge

		
#### Anything else to add?
No

**Comment by emclaug2** [comment]
At this point I think it's safe to close this issue considering we are beginning the redesign of the new component library doc site.
