### ISSUE TITLE
Chevron and non text right component default color

### ISSUE THREAD

**Issue by bkarambe** [brightlayer-ui/react-component-library#327]
Describe the bug
Colour for non text right component and chevron is different than **theme.palette.text.secondary** from MUI theme.

What is the expected behaviour?
Default non-text right component and chevron colour should be **theme.palette.text.secondary** from MUI theme.

What are the steps to reproduce?
Use rightComponent props  for InfoListItem in component's storybook.
Check color CSS property

Screenshots:
<img width="1514" alt="Screenshot 2021-10-19 at 2 19 32 PM" src="https://user-images.githubusercontent.com/25982779/137876825-719cc509-18cf-4b0b-89a7-de856482e9bc.png">

**Comment by joebochill** [comment]
Is this a storybook-only issue or is this present in the showcase as well?

**Comment by joebochill** [comment]
For the most part, this is going to be up to the user to implement correctly if they are using rightComponent (if we add a wrapper that uses secondary color, it will break any text that they might have in the rightComponent). We can make the change for the chevron (currently it is set to 'inherit', so it picks up the text color), but that's about it.

**Comment by jeffvg** [comment]
fix this so the chevron icon is set to gray 500. Any other user provided icons will need to set the color
