### ISSUE TITLE
ILI background color should update when media query value changes

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/react-component-library#342]
See the video below. This is a fairly trivial one.

#### What are the steps to reproduce?
1. Go to React Design Pattern, "/with-local-actions"
2. Hover / Click on the list item for "Language". Observe that nothing happened
3. Shrink to mobile. Observe that hover color works correctly
4. Shrink back to desktop size
5. Observe that there is an unexpected hover color for the "Language" 

#### Screenshots or links to minimum reproduction example
https://user-images.githubusercontent.com/8997218/145440695-8b6bd240-5b82-416f-a9d5-b3d619814b73.mov

#### Environment
React, Chrome, MacOS
		
#### Anything else to add?
Don't know if this is something we can control at React Design Patterns, ILI, MUI or React.

**Comment by emclaug2** [comment]
It might be a missing dep in the dep array for the style hook; for the on-click prop.

**Comment by ektasawant** [comment]
I have fixed this issue in React Design Pattern https://github.com/brightlayer-ui/react-design-patterns/pull/129. If we are ok with this solution I can transfer this issue in React Design Pattern.

**Comment by joebochill** [comment]
Yes, except we are _actually_ going to switch to MUI 5
