### ISSUE TITLE
Upgrade to using MUI v5

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/react-component-library#352]
#### Describe the desired behavior
Update library to use the latest MUI v5 (@mui/material)

#### Describe the current behavior
We are using the old version 4.x

#### Is this request related to a current issue?
No

#### Additional Context

MUI v5 came out late last year and is a substantial overhaul from v4

**Comment by ektasawant** [comment]
PR for this issue is merged. Closing this issue
