### ISSUE TITLE
App Bar with New Config Storybook story, the Three Liner is positioned higher than they should be

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/react-component-library#368]
#### Describe the bug

The vertical position of the Three Liner component is too high in the field. The "with Dynamic Content" seemed OK though

#### What is the expected behavior?

From DSM

![image](https://user-images.githubusercontent.com/8997218/151010185-66b30c5d-4a9b-4e53-bdae-055004d4ade1.png)

From the Figma file "Collapsible App Bar"

![image](https://user-images.githubusercontent.com/8997218/151010350-0e3de2a5-1e46-4f5e-8fd0-1e4295093020.png)

#### What are the steps to reproduce?
1. Go to https://brightlayer-ui-components.github.io/react-dev/?path=/story/components-app-bar--with-full-config

#### Screenshots or links to minimum reproduction example

![image](https://user-images.githubusercontent.com/8997218/151010452-ffca98fc-2f5e-47d6-88dd-20f0de5c6117.png)

**Comment by emclaug2** [comment]
The storybook story needs to be updated to apply the correct css `top` value.  This shouldn't directly affect the component.

**Comment by emclaug2** [comment]
We currently aren't updating our storybook unless we want to do a manual deploy; we can fix this when we re-implement this example in our new component docs.
