### ISSUE TITLE
Update latest version of @types/react

### ISSUE THREAD

**Issue by ektasawant** [brightlayer-ui/react-component-library#390]
#### Describe the bug
There is an issue in latest version of @types/react (17.0.41)
Issue link [31932](https://github.com/mui/material-ui/issues/31932). React component library build fails with ref error(screenshot attached). To fix this we have added below line in drawerBody.tsx(https://github.com/brightlayer-ui/react-component-library/blob/mui-v5/components/src/core/Drawer/DrawerBody.tsx#L74) and drawerNavItem.tsx (https://github.com/brightlayer-ui/react-component-library/blob/mui-v5/components/src/core/Drawer/DrawerNavItem.tsx#L442)

#### What is the expected behavior?
Remove ts-ignore when latest version is available for `@types/react`.

#### What are the steps to reproduce?
1. Go to root 
2. remove ts-ignore code from drawerBody.tsx(https://github.com/brightlayer-ui/react-component-library/blob/mui-v5/components/src/core/Drawer/DrawerBody.tsx#L74) and drawerNavItem.tsx (https://github.com/brightlayer-ui/react-component-library/blob/mui-v5/components/src/core/Drawer/DrawerNavItem.tsx#L442)
3. Run yarn build

#### Screenshots or links to minimum reproduction example
<img width="1119" alt="159256476-f31b8485-37fc-4740-af51-876618e15d15" src="https://user-images.githubusercontent.com/10433274/159675565-83f0d706-8b3e-4c60-b44a-b6dce5d983ef.png">

#### Environment

All

**Comment by joebochill** [comment]
Is this still an issue? type/react version 18 is out now
