### ISSUE TITLE
Update component docs

### ISSUE THREAD

**Issue by daileytj** [brightlayer-ui/react-component-library#408]
#### Describe the desired behavior
All of our components should have classes and `sx` global class names definitions in the individual component docs.
There should be a top level document showing the various ways to style our components (inline styles, className, classes, sx)

#### Describe the current behavior
Each individual file is expressing how to use sx and there's no guide showing how to use all various styling options.

**Comment by joebochill** [comment]
Is this done now with the updated docs site?

**Comment by bkarambe** [comment]
Already been adressed.
