### ISSUE TITLE
Update Drawer Nav Item Example page (Dev docs)

### ISSUE THREAD

**Issue by ektasawant** [brightlayer-ui/react-component-library#478]
#### Describe the desired behavior
Add example for showing how we can render the `<DrawerNavItem>` as a link by setting the `component` prop in the `InfoListItemProps` to a [`Link`](https://reactrouter.com/web/api/Link) component from `react-router-dom` (recommended), or the native HTML anchor tag `'a'`. This allows you to perform helpful actions such as opening a link in a new browser tab via right-click.
#### Describe the current behavior
No example available
#### Additional Context

Remove following tip section from API docs page.

### Tips

You can render the `<DrawerNavItem>` as a link by setting the `component` prop in the `InfoListItemProps` to a [`Link`](https://reactrouter.com/web/api/Link) component from `react-router-dom` (recommended), or the native HTML anchor tag `'a'`. This allows you to perform helpful actions such as opening a link in a new browser tab via right-click.

**Comment by daileytj** [comment]
fixed in #475
