### ISSUE TITLE
Dev doc line highlighting misplaced

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/react-component-library#485]
#### Describe the bug

In the current dev doc drawer nav item examples, the code block line highlighting is not properly aligned with the code snippet. Something similar happened on the Angular side too, but Evan wisely fixed it (https://github.com/brightlayer-ui/angular-component-library/pull/458#issuecomment-1198130174)

Component is not highlighted when array is passed as a prop. For e.g.
<img width="1489" alt="Screenshot 2022-09-30 at 2 10 18 PM" src="https://user-images.githubusercontent.com/25982779/193230248-7f3ca89d-8eb4-438c-bc40-b2184c6af4e8.png">

#### Screenshots or links to minimum reproduction example

<img width="973" alt="image" src="https://user-images.githubusercontent.com/8997218/185191557-3417fae7-6ab1-4176-a887-234ab000b815.png">
Notice how the bottom edge of that background gradient is going through the middle of a line

**Comment by jeffvg** [comment]
This might need a custom style override to align highlight

**Comment by huayunh** [comment]
BLUI-3501
