### ISSUE TITLE
Drawer Nav Group ScrollBar

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/react-component-library#490]
#### Describe the bug
Scroll bar is appearing when opening/closing Drawer.

#### What is the expected behavior?
No scrollbar should appear (horizontal)

#### What are the steps to reproduce?
https://github.com/brightlayer-ui/react-component-library/pull/488#issuecomment-1226074736

#### Screenshots or links to minimum reproduction example
https://github.com/brightlayer-ui/react-component-library/pull/488#issuecomment-1226074736

#### Environment

Windows Chrome 		

#### Anything else to add?
No

**Comment by daileytj** [comment]
Can't reproduce, there have been many changes since this issue was written. Closing this issue
