### ISSUE TITLE
All Dev Doc pages should be responsive

### ISSUE THREAD

**Issue by daileytj** [brightlayer-ui/react-component-library#500]
#### Describe the bug
The Dev Doc playground isn't fully responsive. At certain window sizes the drawers overlay the main content without the ability to hide them. Theres some content backgrounds that don't fill the entire background so the main background color appears where it shouldn't and some pages scroll horizontally. There's a spot where the `Menu` icon appears despite the drawer being open. These are just some of my findings. Please see the screenshots below and be sure to test the site on various devices and screen widths to ensure all things are reasonably responsive.

#### What is the expected behavior?
Dev Doc playground should be responsive

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/13989985/188670835-c490dfbe-2261-4adf-adaf-ec876ad46608.png)
![Screen Shot 2022-09-06 at 10 19 39 AM](https://user-images.githubusercontent.com/13989985/188670857-60e56309-169c-4d11-94e1-8656a08fbb06.png)

**Comment by huayunh** [comment]
I made a story (BLUI-3509) to come up with the design first

**Comment by daileytj** [comment]
This has been migrated to jira. Closing this bug as it will be a larger initiative and can be tracked in jira instead.
