### ISSUE TITLE
Dev Doc playground required props shall be in error state when empty

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/react-component-library#510]
#### Describe the desired behavior

On Dev Doc's playground pages, all required props, such as the `label` field in the list item tag component, should check themselves `onBlur` whether they are empty and show an error message saying "Required" if empty.

#### Describe the current behavior

It does not perform a check.

**Comment by huayunh** [comment]
BLUI-3513

**Comment by daileytj** [comment]
This has been fixed already
