### ISSUE TITLE
"Copy all" Button in Dev Doc playground shall use Blue200

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/react-component-library#540]
1. It shalt use blue200 instead of blue500 for the blue color; sorta like how buttons are styled in the dark theme
2. It shalt have a button background color to occlude text behind it

This
![image](https://user-images.githubusercontent.com/8997218/191332864-6da74dfd-7c7c-4e66-9687-7f84e9d0458e.png)

Shall be this:
![image](https://user-images.githubusercontent.com/8997218/191332480-14be87f4-1134-4a1f-a4bc-5d26bdf5f67c.png)

**Comment by bkarambe** [comment]
BLUI-3532

**Comment by ektasawant** [comment]
Fixed here https://github.com/brightlayer-ui/react-component-library/pull/564
