### ISSUE TITLE
Condensed Rail Item height and Width should be 56x56

### ISSUE THREAD

**Issue by bkarambe** [brightlayer-ui/react-component-library#541]
#### Describe the bug
While using DrawerRailItem with condensed property, it seems to render with size 72x72

#### What is the expected behavior?
Condensed drawer rail item size should be 56x56

#### What are the steps to reproduce?
1. cd docs
2. yarn start
3. Navigate to Drawer->Rail item->examples-> Rail Condensed

#### Screenshots or links to minimum reproduction example
<img width="398" alt="Screenshot 2022-09-21 at 1 19 30 PM" src="https://user-images.githubusercontent.com/25982779/191447253-0a2ffe6a-b6ca-4128-8d2a-dbe1baaca25c.png">

**Comment by bkarambe** [comment]
BLUI-3533

**Comment by ektasawant** [comment]
Fixed in this PR https://github.com/brightlayer-ui/react-component-library/pull/563
