### ISSUE TITLE
Console warning while navigating to Tollbar Menu dev docs

### ISSUE THREAD

**Issue by bkarambe** [brightlayer-ui/react-component-library#586]
#### Describe the bug
There is a console warning while navigating to Toolbar menu examples on localhost. Does not apply to deployed versions.

#### What is the expected behavior?
Page should render without console warning
https://github.com/brightlayer-ui/react-component-library/pull/583#issuecomment-1271075460

#### What are the steps to reproduce?
1. yarn start:reactdev
2. Navigate to Toolbar Menu

#### Screenshots / Screen recording
<img width="1792" alt="Screenshot 2022-10-07 at 12 21 32 PM" src="https://user-images.githubusercontent.com/25982779/194486598-d588d1f6-4f7a-40fa-8b89-f870263af226.png">

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by daileytj** [comment]
fixed
