### ISSUE TITLE
App Bar not taking default value if collapsedHeight or expandedHeight is empty

### ISSUE THREAD

**Issue by ektasawant** [brightlayer-ui/react-component-library#591]
#### Describe the bug
App Bar not taking default value if collapsedHeight or expandedHeight is empty.
#### What is the expected behavior?
App Bar should tak default value if collapsedHeight or expandedHeight is empty.
#### What are the steps to reproduce?
1. Go to Dev docs - /components/app-bar/playground
2. remove number from  collapsedHeight prop i.e pass empty string
3. remove number from  expandedHeight prop i.e pass empty string

The app bar starts misbehaving (Check below recording)

#### Screenshots / Screen recording
https://user-images.githubusercontent.com/8997218/194061258-0762d624-a980-4e8e-9c56-e43cda9406ad.mov
#### Code snippet / Link to minimum reproduction example

```
[CODE HERE](https://github.com/brightlayer-ui/react-component-library/blob/dev/components/src/core/AppBar/AppBar.tsx#L85)
https://github.com/brightlayer-ui/react-component-library/blob/dev/components/src/core/AppBar/AppBar.tsx#L92
```

#### Your environment information

All

**Comment by daileytj** [comment]
This issue has been fixed
