### ISSUE TITLE
Components do not work with latest version of MUI

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/react-component-library#622]
#### Describe the bug
When creating a new project using the BLUI CLI, the project will not run. An error appears in the console about generateUtilityClasses from mui/base.

#### What is the expected behavior?
A new project should run successfully after generating with the CLI.

#### What are the steps to reproduce?
1. `npx -p @brightlayer-ui/cli blui new react`
2. Name your project and select the routing template
3. Run the project
4. Observe that nothing loads and there is an error in the console

#### Screenshots / Screen recording

![image](https://user-images.githubusercontent.com/29152776/198892112-84c8aaae-a219-4599-b648-2e85a12c68b9.png)

#### Code snippet / Link to minimum reproduction example
N/A

#### Your environment information

`@mui/material@5.10.11`

#### Suggested fix

This looks to be a recent change in MUI with regards to the 'unstable' version of this function. The latest version of the MUI components import this function from `@mui/material/generateUtilityClasses` instead of `@mui/base`.

#### Anything else to add?
Dropping to 5.5.x makes the components work again. The change in MUI happened between 5.5.0 and 5.10.11

**Comment by daileytj** [comment]
fixed in https://github.com/brightlayer-ui/react-component-library/pull/638
